import = ["~/.config/alacritty/themes/themes/iceberg.toml"]

[font]
size = 15

[font.normal]
family = "Monaspace Neon"
style = "Regular"

[font.bold]
family = "Monaspace Neon"
style = "Bold"

[font.italic]
family = "Monaspace Neon"
style = "Italic"

[window]
opacity = 0.9

[shell]
program = "/bin/zsh"
args = ["-l", "-c", "tmux a -t default || tmux new -s default\\;"]
