import = ["themes/themes/iceberg.toml"]

[font]
size = 15

[font.normal]
family = "SauceCodePro Nerd Font"
style = "Regular"

[font.bold]
family = "SauceCodePro Nerd Font"
style = "Bold"

[font.italic]
family = "SauceCodePro Nerd Font"
style = "Italic"

[window]
opacity = 0.9

[shell]
program = "/usr/bin/bash"
args = ["-l", "-c", "tmux a -t default || tmux new -s default\\;"]
