-- local wk = require('which-key')
--
-- wk.setup()
--
-- wk.register({
--   ["<C-l>"] = 'Whole lines',
--   ["<C-n>"] = 'keywords in the current file',
--   ["<C-k>"] = 'keywords in dictionary',
--   ["<C-t>"] = 'keyworkds in thesaurus',
-- }, {
--   mode = "i",
--   prefix = "<C-x>",
-- })
