import = ["themes/themes/iceberg.toml"]

[env]
TERM = "alacritty-direct"

[font]
size = 16

[font.normal]
family = "Moralerspace Argon NF"
style = "Regular"

[font.bold]
family = "Moralerspace Argon NF"
style = "Bold"

[font.italic]
family = "Moralerspace Argon NF"
style = "Italic"

[window]
opacity = 0.9

[shell]
program = "/usr/bin/fish"
args = ["-l", "-c", "tmux a -t default || tmux new -s default\\;"]
