[general]
import = ["themes/themes/nightfox.toml"]

[env]
TERM = "alacritty-direct"

[font]
size = 18

[font.normal]
family = "Moralerspace Neon HWNF"
style = "Regular"

[font.bold]
family = "Moralerspace Neon HWNF"
style = "Bold"

[font.italic]
family = "Moralerspace Neon HWNF"
style = "Italic"

[window]
opacity = 0.9

[terminal]

[terminal.shell]
program = "/usr/bin/fish"
# args = ["-l", "-c", "tmux a -t default || tmux new -s default\\;"]
